# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage unittest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python3 tests/run_tests.py
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 1f36184b6aa62d6fcf0154f6ec46db1dcd88bb27bcd277659a9b513d09940a46
      with:
        coverageCommand: coverage run -m unittest discover
